import type { Product } from "@/types";

export const products: Product[] = [
  { id: "1", name: "Aurora Noise-Canceling Headphones", price: 299, category: "Audio", rating: 4.6, image: "/api/placeholder/400/320" },
  { id: "2", name: "Nebula Smart Speaker", price: 149, category: "Audio", rating: 4.2, image: "/api/placeholder/400/320" },
  { id: "3", name: "Pulse Wireless Earbuds", price: 89, category: "Audio", rating: 4.1, image: "/api/placeholder/400/320" },
  { id: "4", name: "Lumen Studio Microphone", price: 199, category: "Audio", rating: 4.7, image: "/api/placeholder/400/320" },
  { id: "5", name: "Vertex Gaming Headset", price: 179, category: "Audio", rating: 4.4, image: "/api/placeholder/400/320" },
  { id: "6", name: "Zenith 4K HDR Monitor", price: 1099, category: "Electronics", rating: 4.8, image: "/api/placeholder/400/320" },
  { id: "7", name: "Atlas Ultrabook 14\"", price: 1599, category: "Electronics", rating: 4.5, image: "/api/placeholder/400/320" },
  { id: "8", name: "Nimbus Tablet Pro", price: 899, category: "Electronics", rating: 4.3, image: "/api/placeholder/400/320" },
  { id: "9", name: "Quasar Portable Charger", price: 69, category: "Electronics", rating: 4.0, image: "/api/placeholder/400/320" },
  { id: "10", name: "Ion Smartwatch Series 5", price: 349, category: "Electronics", rating: 4.4, image: "/api/placeholder/400/320" },
  { id: "11", name: "Nova AR Glasses", price: 1199, category: "Electronics", rating: 4.2, image: "/api/placeholder/400/320" },
  { id: "12", name: "Helix Mechanical Keyboard", price: 199, category: "Electronics", rating: 4.6, image: "/api/placeholder/400/320" },
  { id: "13", name: "Coda Bluetooth MIDI Controller", price: 499, category: "Electronics", rating: 4.3, image: "/api/placeholder/400/320" },
  { id: "14", name: "Stride Performance Running Shoes", price: 129, category: "Footwear", rating: 4.5, image: "/api/placeholder/400/320" },
  { id: "15", name: "Summit Gore-Tex Hiking Boots", price: 249, category: "Footwear", rating: 4.8, image: "/api/placeholder/400/320" },
  { id: "16", name: "Velocity Knit Sneakers", price: 159, category: "Footwear", rating: 4.1, image: "/api/placeholder/400/320" },
  { id: "17", name: "Gravity Powerlifting Shoes", price: 199, category: "Footwear", rating: 4.4, image: "/api/placeholder/400/320" },
  { id: "18", name: "Momentum Trail Runners", price: 189, category: "Footwear", rating: 4.6, image: "/api/placeholder/400/320" },
  { id: "19", name: "Aether Minimalist Sneakers", price: 139, category: "Footwear", rating: 4.2, image: "/api/placeholder/400/320" },
  { id: "20", name: "Mosaic Leather Tote", price: 329, category: "Accessories", rating: 4.5, image: "/api/placeholder/400/320" },
  { id: "21", name: "Flux Titanium Sunglasses", price: 229, category: "Accessories", rating: 4.7, image: "/api/placeholder/400/320" },
  { id: "22", name: "Vector Premium Backpack", price: 269, category: "Accessories", rating: 4.6, image: "/api/placeholder/400/320" },
  { id: "23", name: "Echo Smart Wallet", price: 119, category: "Accessories", rating: 4.1, image: "/api/placeholder/400/320" },
  { id: "24", name: "Orbit Travel Duffel", price: 189, category: "Accessories", rating: 4.3, image: "/api/placeholder/400/320" },
  { id: "25", name: "Axis Modular Belt", price: 89, category: "Accessories", rating: 3.9, image: "/api/placeholder/400/320" },
  { id: "26", name: "Titanium Aviator Watch", price: 749, category: "Accessories", rating: 4.6, image: "/api/placeholder/400/320" },
  { id: "27", name: "Pulse Fitness Tracker", price: 169, category: "Accessories", rating: 4.2, image: "/api/placeholder/400/320" },
  { id: "28", name: "Arcade Streetwear Sneakers", price: 219, category: "Footwear", rating: 4.0, image: "/api/placeholder/400/320" },
  { id: "29", name: "Quantum Studio Monitor Speakers", price: 1299, category: "Audio", rating: 4.9, image: "/api/placeholder/400/320" },
  { id: "30", name: "Nebula VR Headset", price: 1999, category: "Electronics", rating: 4.7, image: "/api/placeholder/400/320" }
];
